name: SMPRPG
version: '${version}'
main: xyz.devvydont.smprpg.SMPRPG
bootstrapper: xyz.devvydont.smprpg.SMPRPGBootstrapper
api-version: '26.1.2'

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    ProtocolLib:
      load: BEFORE
      required: true
    CraftEngine:
      load: BEFORE
      required: true
      join-classpath: true
    BetterModel:
      load: BEFORE
      required: true
      join-classpath: true
    WorldGuard:
      load: BEFORE
      required: false