package xyz.devvydont.smprpg.util.items
import xyz.devvydont.smprpg.util.items.ToolGlobals.*

enum class ToolStats(val durability: Int, val power: Int, val fortune: Int, val speed: Int, val miningPower: Int) {
    WOOD(WOOD_TOOL_DURABILITY, WOOD_TOOL_POWER, WOOD_TOOL_FORTUNE, WOOD_TOOL_SPEED, WOOD_TOOL_MINING_POWER),

    COPPER(COPPER_TOOL_DURABILITY, COPPER_TOOL_POWER, COPPER_TOOL_FORTUNE, COPPER_TOOL_SPEED, COPPER_TOOL_MINING_POWER),
    TIN(TIN_TOOL_DURABILITY, TIN_TOOL_POWER, TIN_TOOL_FORTUNE, TIN_TOOL_SPEED, TIN_TOOL_MINING_POWER),
    SILVER(SILVER_TOOL_DURABILITY, SILVER_TOOL_POWER, SILVER_TOOL_FORTUNE, SILVER_TOOL_SPEED, SILVER_TOOL_MINING_POWER),

    IRON(IRON_TOOL_DURABILITY, IRON_TOOL_POWER, IRON_TOOL_FORTUNE, IRON_TOOL_SPEED, IRON_TOOL_MINING_POWER),
    BRONZE(BRONZE_TOOL_DURABILITY, BRONZE_TOOL_POWER, BRONZE_TOOL_FORTUNE, BRONZE_TOOL_SPEED, BRONZE_TOOL_MINING_POWER),
    ROSE_GOLD(ROSE_GOLD_TOOL_DURABILITY, ROSE_GOLD_TOOL_POWER, ROSE_GOLD_TOOL_FORTUNE, ROSE_GOLD_TOOL_SPEED, ROSE_GOLD_TOOL_MINING_POWER),
    GOLD(GOLD_TOOL_DURABILITY, GOLD_TOOL_POWER, GOLD_TOOL_FORTUNE, GOLD_TOOL_SPEED, GOLD_TOOL_MINING_POWER),

    STEEL(STEEL_TOOL_DURABILITY, STEEL_TOOL_POWER, STEEL_TOOL_FORTUNE, STEEL_TOOL_SPEED, STEEL_TOOL_MINING_POWER),
    MITHRIL(MITHRIL_TOOL_DURABILITY, MITHRIL_TOOL_POWER, MITHRIL_TOOL_FORTUNE, MITHRIL_TOOL_SPEED, MITHRIL_TOOL_MINING_POWER),

    TITANIUM(TITANIUM_TOOL_DURABILITY, TITANIUM_TOOL_POWER, TITANIUM_TOOL_FORTUNE, TITANIUM_TOOL_SPEED, TITANIUM_TOOL_MINING_POWER),
    ADAMANTIUM(ADAMANTIUM_TOOL_DURABILITY, ADAMANTIUM_TOOL_POWER, ADAMANTIUM_TOOL_FORTUNE, ADAMANTIUM_TOOL_SPEED, ADAMANTIUM_TOOL_MINING_POWER),

    TUNGSTEN(TUNGSTEN_TOOL_DURABILITY, TUNGSTEN_TOOL_POWER, TUNGSTEN_TOOL_FORTUNE, TUNGSTEN_TOOL_SPEED, TUNGSTEN_TOOL_MINING_POWER),

    COBALT(COBALT_TOOL_DURABILITY, COBALT_TOOL_POWER, COBALT_TOOL_FORTUNE, COBALT_TOOL_SPEED, COBALT_TOOL_MINING_POWER),
    ORICHALCUM(ORICHALCUM_TOOL_DURABILITY, ORICHALCUM_TOOL_POWER, ORICHALCUM_TOOL_FORTUNE, ORICHALCUM_TOOL_SPEED, ORICHALCUM_TOOL_MINING_POWER),

    NETHERITE(NETHERITE_TOOL_DURABILITY, NETHERITE_TOOL_POWER, NETHERITE_TOOL_FORTUNE, NETHERITE_TOOL_SPEED, NETHERITE_TOOL_MINING_POWER),

    DRAGONSTEEL(DRAGONSTEEL_TOOL_DURABILITY, DRAGONSTEEL_TOOL_POWER, DRAGONSTEEL_TOOL_FORTUNE, DRAGONSTEEL_TOOL_SPEED, DRAGONSTEEL_TOOL_MINING_POWER);

    fun getArmorUnitDurability() : Double {
        return durability / 8.0
    }
}